### PR TITLE
feat: customized input UI component to support password visibility to…

### PR DESCRIPTION
**Pull request by cybertron15**
## What does this PR do?
I customized the input UI component to support password visibility toggle feature in both LIGHT and DARK mode. So whenever we use input component and set type='password' we'll automatically get the input field with password visibility toggle feature.

Fixes #133 
Fixes #138

Loom Video
[Video](https://www.loom.com/share/887a5764771d4cb4b35162fd9c74d9cb?sid=c229711d-b47f-4f1f-8d8c-cff39c213fb3)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?
you can test this by trying to sign in or signup and try to toggle the password visibility

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by hemantwasthere — CHANGES_REQUESTED** [review]
Can you make the eye icon a little small and please change it's color to match borders of input

**Comment by cybertron15** [comment]
working on it

**Comment by cybertron15** [comment]
made the requested changes @hemantwasthere

**Review by hemantwasthere — APPROVED** [review]
LGTM for now!

**Pull request merged**
