### PR TITLE
fix: Fixes uncontrolled input at signup page

### LINKED ISSUE #13: Warning: Uncontrolled to Controlled Input Transition at signup page
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I encountered a warning message in my React application with the following details:
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen.

### Steps to Reproduce

1. Visit the signup page by navigating to http://app.localhost:3000/signup.
2. On the signup page, locate the "Last Name" input field.
3. Make any changes or edits in the "Last Name" input field.

### Actual Results

- A warning message appears in the console during component rendering, indicating a transition from an uncontrolled input to a controlled input due to a value change.

### Expected Results

- I expected the application to handle input elements consistently, either as controlled or uncontrolled inputs, without triggering warnings of this nature.

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

image

### PR DESCRIPTION
**Pull request by C0dewithLokesh**
## What does this PR do?

I added the `lastName` field to the default values in the `form` object.

Fixes #13

# Demo Video link
https://www.loom.com/share/a240e581a69243e2b4d8abab4039166e?sid=df86630f-53d6-46c4-a5dc-ff14df25cd45

## Demo ScreenShot
- no error even after input changes

image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?
1. Visit the signup page by navigating to http://app.localhost:3000/signup.
2. On the signup page, locate the "Last Name" input field.
3. Make any changes or edits in the "Last Name" input field.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by piyushgarg-dev** [comment]
Hi @C0dewithLokesh, Thanks for contributing.
As per the backend schema, lastName is optional. Is this code taking of that?

**Comment by hemantwasthere** [comment]
@piyushgarg-dev yep, we have zod validation for optional lastname field

**Review by hemantwasthere — APPROVED** [review]

**Comment by piyushgarg-dev** [comment]
Great @hemantwasthere @C0dewithLokesh 
@hemantwasthere You can merge this if everything is good.

Thanks for contributing @C0dewithLokesh 😄

**Review by hemantwasthere — CHANGES_REQUESTED** [review]
There seem to be conflicting checks on lastName field validations on line no 31.
As lastName field is optional so we don't need to have .min() and .max() functions validation.

Please remove these functions `.min(3).max(25)`, just leave only `.optional()` function

**Comment by piyushgarg-dev** [comment]
> There seem to be conflicting checks on lastName field validations on line no 31. As lastName field is optional so we don't need to have .min() and .max() functions validation.
> 
> Please remove these functions `.min(3).max(25)`, just leave only `.optional()` function

@hemantwasthere 
I guess that's alright? 
It's optional but if a user is providing lastName then min and max must be validated.

**Comment by C0dewithLokesh** [comment]
Thank you, @piyushgarg-dev and @hemantwasthere, for reviewing my request. Please let me know if I should remove the "min" and "max" Function validation or not.

**Comment by hemantwasthere** [comment]
> Thank you, @piyushgarg-dev and @hemantwasthere, for reviewing my request. Please let me know if I should remove the "min" and "max" Function validation or not.

Hey @C0dewithLokesh, yeah sure please remove these `min()` and `max()` functions for now. Later on, we have to put a condition something like if the lastName field has some values then it must be within limits elsewise it should be optional.

**Comment by C0dewithLokesh** [comment]
@hemantwasthere, @piyushgarg-dev 
I attempted a solution where we incorporate this functionality into the 'lastName' field. Here's the code for 'lastName':
```
lastName: z.string().refine(
    (value) => value === "" || (value.length >= 3 && value.length <= 25),
    {
      message: 'Last name must be between 3 and 25 characters'
    }
  ).optional(),
```
I've tested it locally, and it's functioning correctly. Please review it; otherwise, I will removing the 'min' and 'max'.

**Comment by hemantwasthere** [comment]
> lastName: z.string().refine(
>     (value) => value === "" || (value.length >= 3 && value.length <= 25),
>     {
>       message: 'Last name must be between 3 and 25 characters'
>     }
>   ).optional(),


Great patch, LGTM 👍

**Comment by C0dewithLokesh** [comment]
hey bro, let me push my code first😅

**Pull request merged**
