### PR TITLE
feat: Landing page

### LINKED ISSUE #169: 🔥 Modern Landing Pages
**Please Read This Carefully 👀**

Review App Requires few landing pages for Homepage, About, etc. It would help if you created stunning landing pages for the home page of the review app. Please feel free to use templates.

Important
- Please keep the page support for both dark and light mode.
- Page must be responsive
- Add animations using your favorite library such as AOL, framer, etc
- While raising a PR, please add a video to showcase your work.
- Please mention the Fixes #issue-number in your PR

Example Pages
- [https://tryleap.ai/](https://tryleap.ai/)
- [https://www.teachyst.com/](https://www.teachyst.com/)
- [https://vercel.com/](https://vercel.com/)

🚨 To avoid merge conflicts, You need to create your landing page under `/pages/templates/<YOUR_GIT_USERNAME>/index.tsx` page.

For example: `/pages/templates/piyushgarg-dev/index.tsx`

**Note: Please don't ask for assigning for the issue. You can start working on this as we require multiple landing pages.**

### PR DESCRIPTION
**Pull request by MokshagnaV**
## What does this PR do?

Under issue  #169 
Created a landing page for review app

Fixes #169 

 Loom Video: https://www.loom.com/share/30e970e1c44a48b8b427eff29be40524?sid=68c7d34e-14dc-41fd-ad39-ba6d8c5b8188

## Requirement/Documentation

- I have used framer-motion and tailwindcss

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Sections Added
- Hero
- Features
- How it works

Please specify any other sections that needs to be added
 *Some images are placed(in how it works section) as a placeholder need to be replaced with original images*

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by piyushgarg-dev** [comment]
Woaa 🎉  My eyes 👀

**Comment by MokshagnaV** [comment]
Added a commit. This commit includes about page of landing page.
Here's the video demo 
Loom video: https://www.loom.com/share/ecaaebe35dff47278659b88c5496d07c?sid=156d3faa-c2b3-460c-9585-0bf1a29284f1

**Comment by Amogh-Nivaskar** [comment]
hey @MokshagnaV your landing page looks great !!! . Can you pls tell me what kind of tools you used for the animations. Thanks

**Comment by MokshagnaV** [comment]
> hey @MokshagnaV your landing page looks great !!! . Can you pls tell me what kind of tools you used for the animations. Thanks

Thank you! I used Framer Motion for the animations. It's a great tool for creating dynamic and smooth animations on web pages.

**Comment by hemantwasthere** [comment]
It looks great but that animating gradient blob hurts in my eyes in dark mode😂

**Comment by MokshagnaV** [comment]
> @MokshagnaV Please also include Issue no in the description
> 
> It looks great but that animating gradient blob hurts in my eyes in dark mode 😂 Can you make it more darkish in the dark mode

Sorry i edited the issue no. now
Sure, I will make it the blob darker

**Comment by MokshagnaV** [comment]
I made the colors darker only in dark mode.
Preview

Please check this and give feedback

**Comment by MokshagnaV** [comment]
I don't know why this PR is closed.
The changes i made(i.e., the landing page) is not committed(merged) in this PR. 
I did new commits on this branch.
I tried to reopen the PR. But i can't
Should i open a new PR?

**Comment by hemantwasthere** [comment]
@MokshagnaV yea you can open a new PR

**Pull request closed without merging**
