### PR TITLE
fix: fixed issue number 71! 

### LINKED ISSUE #71: [Bug]: On Shifting the form panel to the top, the dashboard logo and sidebar is disappearing !
### Describe the bug

image

The Dashboard logo and the sidebar are disappearing when the form panel is shifted to top.

### To Reproduce

image

Expected view is to be something where the logo and sidebar are visible !

### Expected behavior

Mentioned Above !

### Screenshots/Videos

_No response_

### Additional context

_No response_

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

### PR DESCRIPTION
**Pull request by saadabban76**
## What does this PR do?
fix the disappearing sidebar and dashboard logo when the reactQuerydev tools is shifted to top 

Fixes #71 
fix in tailwind css

image
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by piyushgarg-dev** [comment]
Please add fixes #issue-number in description

**Comment by piyushgarg-dev** [comment]
You need to edit Fixes #<NUMBER>
Screenshot 2023-10-08 at 3 28 38 PM

**Comment by saadabban76** [comment]
> You need to edit Fixes # Screenshot 2023-10-08 at 3 29 10 PM

Done 👍🏼

**Review by hemantwasthere — APPROVED** [review]
LGTM

**Pull request merged**
