### PR TITLE
docs: Updated contributing doc where env local had different domains

### PR DESCRIPTION
**Pull request by ArshadChowdhury**
## What does this PR do?

Fixes # (issue)

Updated Contributing.md file where it had only one public domain now we have two so had to update the doc accordingly.

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set? - NO
- What are the minimal test data to have? - N/A
- What is expected (happy path) to have (input and output)? - N/A
- Any other important info that could help to test that PR - N/A

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by hemantwasthere** [comment]
Already resolved!

**Comment by ArshadChowdhury** [comment]
@hemantwasthere bro the doc is not updated according to new env domain.

the previous & current version is this - 

 NEXT_PUBLIC_AWS_API_URL=http://localhost:8000/local
 NEXT_PUBLIC_APP_DASHBOARD_DOMAIN=app
 NEXT_PUBLIC_APP_DOMAIN=localhost:3000
   
the new version should be this - 

NEXT_PUBLIC_AWS_API_URL=
NEXT_PUBLIC_APP_DASHBOARD_DOMAIN=
NEXT_PUBLIC_APP_PUBLIC_DOMAIN=
NEXT_PUBLIC_APP_CUSTOM_DOMAIN=

**Review by hemantwasthere — COMMENTED** [review]
Looks good!

**Comment by ArshadChowdhury** [comment]
Thank you very much, really appreciate it.

**Pull request merged**
