### PR TITLE
feat: dark mode added to the review form

### LINKED ISSUE #233: [Bug]: Form Color in Dark Mode
### Describe the bug

The color of Form is not correct in dark mode

### To Reproduce

Go to the Edit Form Screen and see the form

### Expected behavior

The form must be Dark in bg color

### Screenshots/Videos

Screenshot 2023-10-22 at 5 00 45 PM

### Additional context

_No response_

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

### PR DESCRIPTION
**Pull request by tanpreetjolly**
## What does this PR do?

This PR adds dark mode colors to the ReviewForm

Fixes #233 
Before : 
Screenshot from 2023-10-24 17-36-39

After:
Screenshot from 2023-10-24 17-35-50

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- Create a new form via Dashboard
- Go to the Review Form and check the UI

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by hemantwasthere** [comment]
Hey @tanpreetjolly, This looks good!
Please make all form steps UI visually appealing in dark mode like welcome page, response page, etc.

image

**Comment by tanpreetjolly** [comment]
Allright I will do it with all the form steps

**Comment by tanpreetjolly** [comment]
@hemantwasthere I have added it to all forms now. You can check it out.
Screenshot from 2023-10-24 21-48-57
Screenshot from 2023-10-24 21-47-58
Screenshot from 2023-10-24 21-48-53

**Comment by hemantwasthere** [comment]
> @hemantwasthere I have added it to all forms now. You can check it out. Screenshot from 2023-10-24 21-48-57 Screenshot from 2023-10-24 21-47-58 Screenshot from 2023-10-24 21-48-53

It looks nice, can you also please style the **Powered by Review App** a more darkish?

**Comment by tanpreetjolly** [comment]
All right I will add dark to the "Powered by review part"

**Comment by tanpreetjolly** [comment]
@hemantwasthere  Does this look good? 
image

**Comment by hemantwasthere** [comment]
> @hemantwasthere Does this look good? image

Yeah it looks great!!

**Comment by tanpreetjolly** [comment]
@hemantwasthere 
Alright then , I have pushed all the dark mode commits in this PR. You can check it out

**Review by hemantwasthere — APPROVED** [review]
LGTM!

**Pull request merged**
