### PR TITLE
feat: Add clickable navbar icon that navigates to home page on clicking

### PR DESCRIPTION
**Pull request by rohitcodism**
feat

## What does this PR do?

It changes the icon text into a link instead of a header element. On Clicking the icon it will navigate to home page.

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by hemantwasthere** [comment]
@rohitcodism what issue does this PR resolves??

**Comment by rohitcodism** [comment]
In this code I have just wrapped the icon with a Link element so that it can navigate to homepage on click

**Comment by hemantwasthere** [comment]
> In this code I have just wrapped the icon with a Link element so that it can navigate to homepage on click

@rohitcodism This issue has been already solved so closing the PR and please put the issue no in the description of the PR that it resolves next time.

Thanks for your contribution 💙

**Comment by rohitcodism** [comment]
Okay thanks for considering ☺️

**Pull request closed without merging**
