### PR TITLE
fix: added cursor pointer to theme toggle dropdown items

### LINKED ISSUE #146: [Bug]: Dropdown items for theme toggle has cursor as default
### Describe the bug

The Theme Toggle button's dropdown items have their cursor property set to default.

### To Reproduce

1. Login / Signup and go to dashboard.
2. On the upper right hand corner, click on the theme toggle icon
3. Hover on the themes, you will see that the cursor property is set to default 

### Expected behavior

Since each of the dropdown items in theme toggle button is clickable, the cursor property should be set to pointer.

### Screenshots/Videos

image
image

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

### PR DESCRIPTION
**Pull request by Amogh-Nivaskar**
## What does this PR do?

Makes the cursor property as pointer for the theme toggle dropdown items, since they are clickable

Fixes #146

## Video Demo
https://www.loom.com/share/b98640d571c2435090da6aeb864e6f79

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

1. Login or signup and go to dashboard.
2. On the upper righthand corner, click on the theme toggle button
3. Hover on the dropdown items of theme toggle button
4. You will see that the cursor is set to pointer

### CODE REVIEW

**Review by hemantwasthere — APPROVED** [review]
LGTM

**Review by hemantwasthere — COMMENTED** [review]
Please resolve the conflicts

**Comment by Amogh-Nivaskar** [comment]
> Please resolve the conflicts

yes sir

**Comment by Amogh-Nivaskar** [comment]
@hemantwasthere I have solved the merge conflicts, but since this is my first time working with merge conflicts as I am new to open source, I think I messed up somewhere because I had to commit many files, when I didnt even change them. Please do let me know, if I have to do anything else. Thank you.

**Comment by Amogh-Nivaskar** [comment]
@hemantwasthere I realize that somehow, I have messed up quite a bit while merging branches. This has led to unnecessary branches being merged and thus other files have been merged in. Is it okay if I make another PR for this issue? I think that would make things much easier to solve.

**Comment by hemantwasthere** [comment]
@Amogh-Nivaskar Yeah it's okay make a new PR and close this one!

**Comment by Amogh-Nivaskar** [comment]
Closing This PR and making a new one

**Pull request closed without merging**
